    local PLUGIN = PLUGIN or {

    }

    PLUGIN.Developer = 'ted.lua'
    PLUGIN.Profile = 'http://steamcommunity.com/id/tedlua/'
    PLUGIN.Plugin = 'Weapon Store'

    PLUGIN.ErrorStatus = 'Could not init PLUGIN.'

    --[[
        Do not edit this file, it's pointless.
        If you want to configure this addon, edit:
        sv_init.lua and cl_init respectively.

        If you need help, add me on Steam:
        http://steamcommunity.com/id/tedlua/
    --]]
