    --------------------------------------------------------
    -->DO NOT EDIT THIS FILE WHILE THE SERVER IS RUNNING!<--
    -->DO NOT EDIT THIS FILE WHILE THE SERVER IS RUNNING!<--
    --------------------------------------------------------

    local PLUGIN = PLUGIN or {

    }

    PLUGIN.Developer = 'ted.lua'
    PLUGIN.Profile = 'http://steamcommunity.com/id/tedlua/'
    PLUGIN.Plugin = 'Weapon Store'

    PLUGIN.ErrorStatus = 'Could not init PLUGIN.'
    -------------------------------------------------------
    -- Do not touch if you don't know what you are doing --
    -------------------------------------------------------
    PLUGIN.FolderName, PLUGIN.Directory, PLUGIN.SavedWeapons = 'weapon_store', 'DATA', {}
    PLUGIN.DARKRP_CASH, PLUGIN.POINTSHOP_ONE = 1, 2
    -------------------------------------------------------
    PLUGIN.Donators = {} -- Don't touch.
    PLUGIN.Permanent_Weapons = true -- Do weapons save?
    PLUGIN.CurrencyType = PLUGIN.DARKRP_CASH -- What currency are we using? PLUGIN.DARKRP_CASH or PLUGIN.POINTSHOP_ONE
    -------------------------------------------------------
    --[[
        PLEASE READ BEFORE ASKING ME FOR ASSISTANCE:
        Below is where you will enter in all of the weapons that you'd like.
        name = <The name of the weapon to show>, model = <model of entity to show, get from q menu>,
        entity = <The entity given on purchase, get from q menu>, price = <price>, length = <0 always>,
        cat = <The category to put the weapon in>, donator = <true or false> if true, cat is ignored a overridden
    --]]
    PLUGIN.Weapons = PLUGIN.Weapons or { -- For all weapons that are not VIP, Donator, whatever.
        { name = 'Butterfly (Night)', model = 'models/weapons/w_csgo_butterfly.mdl', entity = 'csgo_butterfly_night', price = 10, length = 0, cat = 'Knives', donator = false },
        { name = 'Huntsman (Night)', model = 'models/weapons/w_csgo_m9.mdl', entity = 'csgo_huntsman_night', price = 1500000, length = 0, cat = 'Knives', donator = false },
        { name = 'Karambit (Oynx)', model = 'models/weapons/w_csgo_karambit.mdl', entity = 'csgo_karambit_night', price = 2250000, length = 0, cat = 'Knives', donator = false },
        { name = 'Karambit (Slaughter)', model = 'models/weapons/w_csgo_karambit.mdl', entity = 'csgo_karambit_slaughter', price = 2000000, length = 0, cat = 'Knives', donator = false },
        { name = 'Falchion (Oynx)', model = 'models/weapons/w_csgo_bowie.mdl', entity = 'csgo_falchion_night', price = 1500000, length = 0, cat = 'Knives', donator = false },
        { name = 'The Classic Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape', price = 925000, length = 0, cat = 'Vapes', donator = false },
        { name = 'The Helium Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape_helium', price = 1250000, length = 0, cat = 'Vapes', donator = false },
        { name = 'The Juicy Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape_juicy', price = 1200000, length = 0, cat = 'Vapes', donator = false },
    	{ name = 'The Medical Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape_medicinal', price = 1500000, length = 0, cat = 'Vapes', donator = false },
    	{ name = 'The Amemrican Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape_american', price = 2000000, length = 0, cat = 'Vapes', donator = false },
    	{ name = 'The Basic Vape', model = 'models/swamponions/vape.mdl', entity = 'weapon_vape', price = 750000, length = 0, cat = 'Vapes', donator = false },
        { name = 'AWP | Redline', model = 'models/weapons/w_snip_awp.mdl', entity = 'blast_awprl', price = 7000000, length = 0, cat = 'Weapons', donator = false },
        { name = 'AWP | Dragonlore', model = 'models/weapons/w_snip_awp.mdl', entity = 'awpdragon', price = 10000000, length = 0, cat = 'Weapons', donator = false },
        { name = 'AK47 | Vulcan', model = 'models/weapons/w_rif_m4a1.mdl', entity = 'clt_akvlcn', price = 6000000, length = 0, cat = 'Weapons', donator = false },
        { name = 'M4A4 | Asiimov', model = 'models/weapons/w_rif_m4a1.mdl', entity = 'clt_m4a4_asim', price = 7000000, length = 0, cat = 'Weapons', donator = false },
        { name = 'Nyan Cat Gun', model = 'models/weapons/w_smg1.mdl', entity = 'weapon_nyangun', price = 4000000, length = 0, cat = 'Weapons', donator = false },
        { name = 'AK-47 Asimov', model = 'models/weapons/w_zakasf.mdl', entity = 'asimovf', price = 3500000, length = 0, cat = 'Weapons', donator = false },
        { name = 'Dab SWEP', model = 'models/weapons/w_smg1.mdl', entity = 'dab', price = 3000000, length = 0, cat = 'Weapons', donator = true }
    }

    PLUGIN.Donators[ 'superadmin' ] = true -- Who can see and purchase from the Donator Section?

    hook.Add( 'PlayerSpawn', 'TEDDY_STORE_CREATE', function()
        if not PLUGIN.Permanent_Weapons then return end
        if !file.IsDir( PLUGIN.FolderName, PLUGIN.Directory ) then
            file.CreateDir( PLUGIN.FolderName )
        end
        if !file.Exists( PLUGIN.FolderName .. '/saves.txt', PLUGIN.Directory ) then
            file.Write( PLUGIN.FolderName .. '/saves.txt', '[]' )
        else
            local data = util.JSONToTable( file.Read( PLUGIN.FolderName .. '/saves.txt', PLUGIN.Directory ) )
            if data then PLUGIN.SavedWeapons = data end
        end
    end )

    function PLUGIN.HasCurrency( self, cost )
        if PLUGIN.CurrencyType == PLUGIN.DARKRP_CASH then
            if !self:canAfford( cost ) then return false end
        elseif PLUGIN.CurrencyType == PLUGIN.POINTSHOP_ONE then
            if !self:PS_HasPoints( cost ) then return false end
        else
            return false
        end
        return true
    end

    function PLUGIN.ChargeCurrency( self, cost )
        if PLUGIN.CurrencyType == PLUGIN.DARKRP_CASH then
            self:addMoney( -cost )
        elseif PLUGIN.CurrencyType == PLUGIN.POINTSHOP_ONE then
            self:PS_TakePoints( cost )
        else
            return false
        end
    end

    function PLUGIN.HasWeapon( self, name )
        if !PLUGIN.SavedWeapons[ self:SteamID() ] then return false end
        for y, x in pairs( PLUGIN.SavedWeapons[ self:SteamID() ] ) do
            if x == name then return true end
        end
        return false
    end

    function PLUGIN.GetEntityName( name )
        for y, x in pairs( PLUGIN.Weapons ) do
            if name == x.name then
                return x.entity
            end
        end
    end

    function PLUGIN.GetTableObject( name )
        for y, x in pairs( PLUGIN.Weapons ) do
            if x.name == name then
                return PLUGIN.Weapons[ y ]
            end
        end
    end

    util.AddNetworkString( 'TEDDY_STORE_ATTEMPT_BUY_WEAPON' )
    net.Receive( 'TEDDY_STORE_ATTEMPT_BUY_WEAPON', function( size, self )
        local name = net.ReadString()
        local object = PLUGIN.GetTableObject( name )
        if !object then return self:ChatPrint( 'This weapon does not exist. Tell a Developer.' ) end
        if object.donator and not PLUGIN.Donators[ self:GetUserGroup() ] then return end -- No exploits here ked x
        if PLUGIN.Permanent_Weapons then
            if not PLUGIN.HasCurrency( self, object.price ) then return self:ChatPrint( 'You can not afford to purchase this.' ) end
            if PLUGIN.SavedWeapons[ self:SteamID() ] and PLUGIN.HasWeapon( self, name ) then
                self:Give( PLUGIN.GetEntityName( name ) )
                self:ChatPrint( "You have withdrawn your " .. name .. "." )
                return
            else
                if not PLUGIN.HasCurrency( self, object.price ) then return self:ChatPrint( 'You can not afford to purchase this.' ) end
                PLUGIN.ChargeCurrency( self, object.price )
                self:ChatPrint( 'You have bought a ' .. name .. ', for ' .. DarkRP.formatMoney( object.price ) .. "." )
            end
            if !PLUGIN.SavedWeapons[ self:SteamID() ] then
                PLUGIN.SavedWeapons[ self:SteamID() ] = { name }
            else
                table.insert( PLUGIN.SavedWeapons[ self:SteamID() ], name )
            end
            timer.Simple( math.random( 0.1, 0.5 ), function() file.Write( PLUGIN.FolderName .. '/saves.txt', util.TableToJSON( PLUGIN.SavedWeapons ) ) end )
        else
            if not PLUGIN.HasCurrency( self, object.price ) then return self:ChatPrint( 'You can not afford this weapon.' ) end
            PLUGIN.ChargeCurrency( self, object.price )
            self:ChatPrint( 'You have bought a ' .. name .. ', for ' .. ( gmod.GetGamemode().Name == 'DarkRP' and DarkRP.formatMoney( object.price ) .. '.' or object.price  .. " Points." ) )
            self:Give( PLUGIN.GetEntityName( name ) )
        end
    end )

    util.AddNetworkString( 'TEDDY_STORE_INTERFACE' )
    function OpenWeaponStore( self ) -- Global, don't kill me please. x
        net.Start( 'TEDDY_STORE_INTERFACE' )
            net.WriteTable( PLUGIN.Weapons )
            net.WriteTable( PLUGIN.SavedWeapons[ self:SteamID() ] or {} )
            net.WriteTable( PLUGIN.Donators )
            net.WriteBool( PLUGIN.Permanent_Weapons )
        net.Send( self )
    end
    
    function PLUGIN.WipeData( self, txt )
        if string.sub( txt, 1, 5 ) == '!wipe' and self:IsSuperAdmin() then
            if PLUGIN.Permanent_Weapons and file.IsDir( PLUGIN.FolderName, PLUGIN.Directory ) then
                file.Write( PLUGIN.FolderName .. '/saves.txt', '[]' )
                self:ChatPrint( 'Data has been reset successfully.' )
            else
                self:ChatPrint( 'Error reseting data.' )
            end
        end
    end
    hook.Add( 'PlayerSay', 'PLUGIN.WeaponStore.Wipe', PLUGIN.WipeData )
